server:
  port: 8080

# spring
# thymeleaf default value
spring:
  thymeleaf:
    enabled: true
    mode: HTML
    encoding: UTF-8
    check-template: true
    check-template-location: true
    prefix: classpath:/templates/page/
    suffix: .html
    cache: true
    enable-spring-el-compiler: false

---
spring:
  config:
    activate:
      on-profile: default,local

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  thymeleaf:
    cache: false