server:
  port: 8080

spring:
  datasource:
    # TODO Type your info
    # ex)
    # driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    # username: user_account
    # password: password
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: username
    password: password


---
spring:
  config:
    activate:
      on-profile: default,local

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false